// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRJWDMjcCrca5uMx-bZNdT3kEvwJMLgec',
    appId: '1:28155504013:web:600a075abb72d2fd6c89c4',
    messagingSenderId: '28155504013',
    projectId: 'social-media-flutter-app-9a302',
    authDomain: 'social-media-flutter-app-9a302.firebaseapp.com',
    storageBucket: 'social-media-flutter-app-9a302.appspot.com',
    measurementId: 'G-NVZ3J914B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16YUanaUeLIDrF2FaOKAs1jFCt3V75kE',
    appId: '1:28155504013:android:0d4d86bd30c908896c89c4',
    messagingSenderId: '28155504013',
    projectId: 'social-media-flutter-app-9a302',
    storageBucket: 'social-media-flutter-app-9a302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbJyzah1S16mAfMRyFzC5DPvI1JG1nbk',
    appId: '1:28155504013:ios:c706cb70038d0b066c89c4',
    messagingSenderId: '28155504013',
    projectId: 'social-media-flutter-app-9a302',
    storageBucket: 'social-media-flutter-app-9a302.appspot.com',
    iosBundleId: 'com.example.socialMediaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbJyzah1S16mAfMRyFzC5DPvI1JG1nbk',
    appId: '1:28155504013:ios:c706cb70038d0b066c89c4',
    messagingSenderId: '28155504013',
    projectId: 'social-media-flutter-app-9a302',
    storageBucket: 'social-media-flutter-app-9a302.appspot.com',
    iosBundleId: 'com.example.socialMediaApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRJWDMjcCrca5uMx-bZNdT3kEvwJMLgec',
    appId: '1:28155504013:web:5d4179ecad3ae6fc6c89c4',
    messagingSenderId: '28155504013',
    projectId: 'social-media-flutter-app-9a302',
    authDomain: 'social-media-flutter-app-9a302.firebaseapp.com',
    storageBucket: 'social-media-flutter-app-9a302.appspot.com',
    measurementId: 'G-YX5K2KWEY2',
  );
}
